name: Create and Publish Docker Image

on:
  workflow_call:


jobs:
  build:
    runs-on: devcloud-rakesh

    steps:      
      
      - name: Set the tag
        run: |
            echo "Hi
            
  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello"
